project 'dome.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'dome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'HandyJSON', '~> 4.1.1'
  # Pods for dome

  target 'domeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'domeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
